FROM node:14.15 as builder

ARG WORK_DIR=/usr/src/app
#use ng serve
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH
WORKDIR ${WORK_DIR}
COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}
RUN npm install @angular/cli
RUN npm install
COPY . ${WORK_DIR}
EXPOSE 4200
CMD ng serve --host 0.0.0.0

